### ISSUE TITLE
Make docs section margins larger

### ISSUE THREAD

**Issue by rmorshea** [idom-team/idom#450]
@Archmonger here's the directory that you should add the CSS to: https://github.com/idom-team/idom/tree/main/docs/source/_static/css

I think this was what you were suggesting:

```css
h1, h2, h3 {
margin-top: 4.5rem;
}
h1, h2 {
margin-bottom: 0;
font-weight: 300;
} 
```
